# Generated by Django 3.2.6 on 2022-08-18 01:32

import Locacao.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '__first__'),
        ('Carros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateField(help_text='Informe a Data de Retirada do Veículo', verbose_name='Data de Retirada')),
                ('data_entrega_prevista', models.DateField(help_text='Informe a data que o veículo deve ser devolvido', verbose_name='Previsão de entrega')),
                ('data_entrega', models.DateField(blank=True, help_text='Informe a data que o veículo foi devolvido', null=True, verbose_name='Data de entrega')),
                ('intencao_uso', models.CharField(help_text='Informe a intenção de utilização do veículo', max_length=100, verbose_name='Intenção de uso')),
                ('cnh', models.IntegerField(help_text='Informe a CNH', verbose_name='CNH')),
                ('carro', models.ForeignKey(help_text='Selecione o Carro', on_delete=django.db.models.deletion.CASCADE, to='Carros.carro', validators=[Locacao.models.valida_carro_data_unico], verbose_name='Carro')),
                ('cliente', models.ForeignKey(help_text='Selecione o Cliente', on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Locação',
                'verbose_name_plural': 'Locações',
            },
        ),
    ]
