# Generated by Django 3.2.6 on 2022-08-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('P', 'Pago'), ('A', 'Aberto'), ('C', 'Cancelado')], default='A', max_length=1),
        ),
    ]
