# Generated by Django 3.2.6 on 2022-08-18 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30)),
                ('marca', models.ForeignKey(default='Modelo Desconhecido', on_delete=django.db.models.deletion.CASCADE, to='Carros.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Informe a placa', max_length=10, verbose_name='Placa do Veículo')),
                ('cor', models.CharField(help_text='Informe a cor', max_length=50, verbose_name='Cor do Veículo')),
                ('ano', models.IntegerField(help_text='Informe o ano', verbose_name='Ano do Veículo')),
                ('qtd_portas', models.CharField(help_text='Informe a quantidade de portas', max_length=50, verbose_name='Quantidade de Portas')),
                ('combustivel', models.CharField(choices=[('DI', 'Diesel'), ('ET', 'Etanol'), ('GA', 'Gasolina'), ('BI', 'Biodisel'), ('EN', 'Elétrico'), ('GN', 'Gás Natural Veicular')], help_text='Informe o tipo de combustível', max_length=2, verbose_name='Tipo de combustível')),
                ('chassi', models.CharField(help_text='Informe o número do chassi', max_length=50, verbose_name='Número do Chassi')),
                ('renavam', models.IntegerField(help_text='Informe o renavam', verbose_name='Renavam')),
                ('nr_hodometro', models.IntegerField(help_text='Informe o Número marcado pelo hodômetro', verbose_name='Número hodômetro')),
                ('valor_locacao', models.DecimalField(decimal_places=2, help_text='Informe o valor', max_digits=19, verbose_name='Valor de Locação')),
                ('status', models.CharField(default='L', editable=False, max_length=1)),
                ('modelo', models.ForeignKey(default='Modelo Desconhecido', help_text='Selecione o modelo do veículo', on_delete=django.db.models.deletion.CASCADE, to='Carros.modelo', verbose_name='Marca/Modelo do Veículo')),
            ],
        ),
    ]
