# Generated by Django 3.2.6 on 2022-08-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome ou razão social', max_length=50, verbose_name='Nome / Razão Social')),
                ('cpf', models.IntegerField(help_text='Informe o CPF ou CNPJ', verbose_name='CPF / CNPJ')),
                ('endereco', models.CharField(help_text='Informe o endereço', max_length=50, verbose_name='Endereço')),
                ('telefone', models.IntegerField(help_text='Informe o Telefone', verbose_name='Telefone')),
            ],
        ),
    ]
